// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getRefreshTokenByToken = `-- name: GetRefreshTokenByToken :one
    SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const logRefreshToken = `-- name: LogRefreshToken :one
    INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
    VALUES ($1, NOW(), NOW(), $2, NOW() + INTERVAL '60 days' , NULL)
    RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type LogRefreshTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) LogRefreshToken(ctx context.Context, arg LogRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, logRefreshToken, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
    UPDATE refresh_tokens SET revoked_at = NOW() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
