// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const changeUserEmailPassword = `-- name: ChangeUserEmailPassword :exec
    UPDATE users SET email = $2, hashed_password = $3, updated_at = NOW() WHERE id = $1
`

type ChangeUserEmailPasswordParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) ChangeUserEmailPassword(ctx context.Context, arg ChangeUserEmailPasswordParams) error {
	_, err := q.db.ExecContext(ctx, changeUserEmailPassword, arg.ID, arg.Email, arg.HashedPassword)
	return err
}

const createUser = `-- name: CreateUser :one
    INSERT INTO users (id, created_at, updated_at, email, hashed_password) VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2)
    RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteUsers = `-- name: DeleteUsers :exec
    DELETE FROM USERS
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
    SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
    SELECT id, created_at, updated_at, email, hashed_password, is_chirpy_red FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const redUpgrade = `-- name: RedUpgrade :exec
    UPDATE users SET is_chirpy_red = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) RedUpgrade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, redUpgrade, id)
	return err
}
